# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'camClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for camClient
end

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'camClient' do
    pod 'Alamofire', '~> 4.4'
end
